### ISSUE TITLE
Problem with docker container (Slow Storage Drive)

### ISSUE THREAD

**Issue by GmasteR** [MaynardMiner/SWARM#17] opened 2019-03-09 00:59 UTC
Hi! Im try to run your scripts, and get errors in screen NVIDIA1:
# export LD_LIBRARY_PATH=/root/SWARM.2.0.3/build/export
# cd
# cd /root/SWARM.2.0.3/./bin/bminer-1
# ./NVIDIA1-2 -uri beam://3JfBiUZZV17DTjAFCnZb97UpBgtLPLLDop.swarm3_7@beam..nicehash.com:3370 -api 127.0.0.1:44000 2>&1 | tee /root/SWARM.2.0.3/logs/NVIDIA1.log
[ERRO] [2019-03-09T00:57:58Z] Unable to locate ./NVIDIA1-2!

**Comment by incodemines** [comment] 2019-03-09 01:59
Others reported this same problem. Do you have access to the SWARM Discord server? He was able to address it for other users who had the same issue as you. It has to do with a script not waiting long enough, I believe he’s working on a patch for it but it hasn’t been released yet. If you can join us on Discord you can see more about it there. Sorry I’m not more help to you, I’m certain he’ll have it fixed before the end of the weekend though.

**Comment by MaynardMiner** [comment] 2019-03-09 02:24
https://github.com/MaynardMiner/SWARM/blob/beta_testing/build/powershell/launchcode.ps1

**Comment by MaynardMiner** [comment] 2019-03-09 02:25
That is the fix

The issue is that on slower drivers the bash startup script is operating faster than the hard drive can read/write.

**Comment by MaynardMiner** [comment] 2019-03-09 02:27
Specifically-

At Line 204:

Start-Sleep -S 1

Adding the 1 second wait gives time for the hard drive to catch up.

I'm going to release fix soon, I am just trying to compile new xmr-stak & xmrig-amd for cryptonight forks first + testing.

**Comment by MaynardMiner** [comment] 2019-03-09 02:31
https://github.com/MaynardMiner/SWARM/issues/14

Noting this is duplicate issue for other users to reference.

**Comment by GmasteR** [comment] 2019-03-09 23:41
I think problem not with my disk drive. 
Im using very fast samsung evo ssd

**Comment by MaynardMiner** [comment] 2019-03-11 05:28
should be fixed as of 2.0.4 release.

**Closed by MaynardMiner** 2019-03-11 05:28 UTC
Labels: bug, duplicate, enhancement
