### ISSUE TITLE
gminer benchmark incorrectly saves hashrate (Related To Windows .NET Russian Formatting)

### ISSUE THREAD

**Issue by petrovsky34** [MaynardMiner/SWARM#121] opened 2019-05-01 08:57 UTC
![gminer](https://user-images.githubusercontent.com/39003568/57011017-2f834a80-6bef-11e9-9fc1-23aac1cc9569.PNG)

**Comment by petrovsky34** [comment] 2019-05-01 08:58
![miniz](https://user-images.githubusercontent.com/39003568/57011024-390cb280-6bef-11e9-9055-4b4b97b8be2a.PNG)

**Comment by petrovsky34** [comment] 2019-05-01 08:59
8x 1050ti 1500 zhash gminer 12 USD

8x 1050ti  zhash miniz 1.50 usd

**Comment by petrovsky34** [comment] 2019-05-01 09:04
gminer 1500 zhash
miniz 160 zhash

**Comment by petrovsky34** [comment] 2019-05-01 11:51
x8 1050 ti biminer 11 gh/s speed

**Comment by petrovsky34** [comment] 2019-05-01 12:09
gminer all algorithms do not show right

**Comment by MaynardMiner** [comment] 2019-05-01 17:29
Okay. I will go the through the API, and see what is going on, but its weird since I don't immediately reproduce. The hashrates seem fine for me.

**Comment by MaynardMiner** [comment] 2019-05-01 17:31
So you are stating:

gminer hashrates are off for you.
bminer ethash is off for you.

Those are the two I will look at.

**Comment by MaynardMiner** [comment] 2019-05-01 17:35
@petrovsky34 Just so I know-

When you run ``benchmark miner gminer-1`` command, and benchmark miner again- Does it continue to produce bad hashrates?

**Comment by MaynardMiner** [comment] 2019-05-01 17:43
Thank you for the feedback btw. It's hard to troubleshoot effectively 4 different OS's/ versions worth of potential issues.

**Comment by MaynardMiner** [comment] 2019-05-01 19:14
For the record, I had three other windows users show me hashrates, and it was correct for them. I am not saying your crazy, because from photos your are not, just this isn't easy to find issue.

**Comment by petrovsky34** [comment] 2019-05-01 20:09
I deleted gminer

**Comment by petrovsky34** [comment] 2019-05-01 20:11
just run swarm gminer benchmark on your computer

**Comment by petrovsky34** [comment] 2019-05-01 20:32
![ffgfg](https://user-images.githubusercontent.com/39003568/57040841-54b49f00-6c69-11e9-9347-604c670f00ff.PNG)
![grdgd](https://user-images.githubusercontent.com/39003568/57040842-54b49f00-6c69-11e9-8570-d8194a4b6db5.PNG)
![vbbvv](https://user-images.githubusercontent.com/39003568/57040843-554d3580-6c69-11e9-9448-e8fef4b4c808.PNG)
![xcvvxvxc](https://user-images.githubusercontent.com/39003568/57040845-554d3580-6c69-11e9-89f5-70b727a56399.PNG)

**Comment by petrovsky34** [comment] 2019-05-01 20:34
![11111](https://user-images.githubusercontent.com/39003568/57040979-b248eb80-6c69-11e9-977d-0cd7e959fba2.PNG)
![22222](https://user-images.githubusercontent.com/39003568/57040980-b248eb80-6c69-11e9-8f50-1761c7f3ac13.PNG)

**Comment by MaynardMiner** [comment] 2019-05-01 20:38
May I see your args? I would like to try to use your settings, to try to reproduce.

**Comment by petrovsky34** [comment] 2019-05-01 20:40
ok
-RigName1 1054 -RigName2 1063 -Algorithm aergo,argon2d-dyn,argon2d4096,allium,bcd,balloon,beam,bitcore,c11,daggerhashimoto,dedal,equihash96,equihash144,equihash192,equihash200,equihash210,ethash,exosis,hex,hmq1725,lbk3,lyra2rev3,lyra2v3,lyra2z,phi,phi2,polytimos,progpow,rainforest,sha256t,skunk,sonoa,timetravel,tribus,verushash,x16r,x16rt,x16s,x17,x21s,x22i,xevan,yescrypt,yescryptr16,yescryptr32,zhash,astralhash,jeonghash,padihash,pawelhash,veil -API Yes -Currency RUB -Location EUROPE -PoolName nicehash,zergpool -Type NVIDIA1,NVIDIA2 -Nicehash_Wallet1 36QFg44C35w2job1yJwkgP16sCFYCJt8jU -Nicehash_Wallet2 36QFg44C35w2job1yJwkgP16sCFYCJt8jU -Wallet1 Xb6b1dtNAbV7epmA7JiVEwmboN9fkxryRa -Wallet2 Xb6b1dtNAbV7epmA7JiVEwmboN9fkxryRa -PasswordCurrency1 DASH -PasswordCurrency2 DASH -Benchmark 220 -Interval 60 -Update Yes -GPUDevices1 0,1,2,3,5,6,8,9 -GPUDevices2 4,7 -Auto_Coin Yes -Startup Yes -Switch_Threshold 5 -SWARM_Mode no -AlgoBanCount 1 -Donate .5 -PoolBanCount 2 -Platform windows -HiveOS No -Farm_Hash 66733112603ad93ace26576c5a2b2c4ce2273501"

**Comment by MaynardMiner** [comment] 2019-05-01 20:47
Okay, I'm looking at it.

For the record, you could probably just cut out the algos you don't want to mine from ``.\config\pools\pool-algos.json`` instead of adding all the algos there. May make life easier, and avoid dealing with typos.

**Comment by petrovsky34** [comment] 2019-05-01 20:51
ok

**Comment by petrovsky34** [comment] 2019-05-01 20:54
thanks

**Comment by MaynardMiner** [comment] 2019-05-01 20:54
The background agent is what gathers the stats, does it look incorrect as well?

**Comment by petrovsky34** [comment] 2019-05-01 21:02
![43t453453](https://user-images.githubusercontent.com/39003568/57042524-8def0e00-6c6d-11e9-8da0-6060a7c703fc.PNG)

**Comment by petrovsky34** [comment] 2019-05-01 21:03
The background agent correctly shows!

**Comment by MaynardMiner** [comment] 2019-05-01 21:04
So the background agent is recording the right stats it seems, but for some reason when SWARM goes to read, it- Is pulling incorrect value.

Swarm saves the Hashrate to a debug file:

``.\build\txt\NVIDIA1-Hash.txt``

Does that value change correctly?

**Comment by MaynardMiner** [comment] 2019-05-01 21:06
Also, you are not running out disk space, right?

**Comment by petrovsky34** [comment] 2019-05-01 21:06
yes correctly shows!  NVIDIA1-Hash.txt

**Comment by MaynardMiner** [comment] 2019-05-01 21:08
So when it pulls from that file, some how the figure it getting messed up. This is a very weird read-write parsing issue. I'm going to see what I can do. But now I know what to look at. thx

**Comment by petrovsky34** [comment] 2019-05-01 21:08
ok

**Comment by petrovsky34** [comment] 2019-05-01 21:11
miniz correctly shows

**Comment by petrovsky34** [comment] 2019-05-01 21:12
![6666666666666666666666](https://user-images.githubusercontent.com/39003568/57042987-ef63ac80-6c6e-11e9-858b-49ca94e16104.PNG)

**Comment by petrovsky34** [comment] 2019-05-01 21:13
![vvvvvvvvvvvvvvvvvvvvvvvvvvv](https://user-images.githubusercontent.com/39003568/57043038-0f936b80-6c6f-11e9-8cd0-bda99b4d846c.PNG)

**Comment by MaynardMiner** [comment] 2019-05-01 21:13
It it written to file with a "," instead of a "." ?

**Comment by petrovsky34** [comment] 2019-05-01 21:14
no

**Comment by petrovsky34** [comment] 2019-05-01 21:15
that this means red written

**Comment by MaynardMiner** [comment] 2019-05-01 21:18
http://nist.time.gov/actualtime.cgi     Does that link work for you?

I think the NIST may be a timedate language issue. I will look into it.

Line 643 is systeminfo (Last photo)

I am looking for "Total Physical Memory", does it not print out in english? That may be why that is failing.

You can open cmd and type ``systeminfo``, and see what language it is printed in.

**Comment by petrovsky34** [comment] 2019-05-01 21:21
![99999999999999999999](https://user-images.githubusercontent.com/39003568/57043440-2ab2ab00-6c70-11e9-9f8e-d7833307ac36.PNG)

**Comment by MaynardMiner** [comment] 2019-05-01 21:21
That's why, its not in english. lol

I will see if there is a way to force it to output as english, so I can parse.

**Comment by petrovsky34** [comment] 2019-05-01 21:23
I from Russia Russian language

**Comment by MaynardMiner** [comment] 2019-05-01 21:24
Yeah. I noticed.

There must be a way I can temporarily change the language of output for developing purposes, so I can parse non-english windows commands. It's something I am not familiar with, but will research ASAP.

**Comment by petrovsky34** [comment] 2019-05-01 21:25
ok

**Comment by petrovsky34** [comment] 2019-05-01 21:33
windows 8 swarm does not work ???

**Comment by MaynardMiner** [comment] 2019-05-01 21:35
.\build\powershell\hashrates.ps1  At line 99, function Get Hashrates


```
function Get-HashRate {
    param(
        [Parameter(Mandatory = $true)]
        [String]$Type,
        [Parameter(Mandatory = $false)]
        [String]$API,
        [Parameter(Mandatory = $false)]
        [Int]$Port
    )

        $HashFile = Get-Content ".\build\txt\$Type-hash.txt"
        [Double]$HashFile
}
```

Try changing

```
[Double]$HashFile
```
to
```
[Decimal]$HashFile
```
See if that corrects the value.

**Comment by petrovsky34** [comment] 2019-05-01 21:36
ok

**Comment by petrovsky34** [comment] 2019-05-01 21:40
no
![5555555555555555555555555555555555](https://user-images.githubusercontent.com/39003568/57044307-db21ae80-6c72-11e9-9d17-a8190ab20401.PNG)

**Comment by petrovsky34** [comment] 2019-05-01 21:41
gminer1 150hs
gminer2 69hs
must be

**Comment by MaynardMiner** [comment] 2019-05-01 21:41
Can I see the contents of NVIDIA1-hash.txt. It should just be a number.

But I want to play with the pwsh culture, and see if I can make it fail.

**Comment by petrovsky34** [comment] 2019-05-01 21:44
![ккккккккккккккккккккккккккк](https://user-images.githubusercontent.com/39003568/57044484-5f743180-6c73-11e9-9773-540b6c1e6b59.PNG)

**Comment by MaynardMiner** [comment] 2019-05-01 21:49
PS C:\Users\Mayna> $A = "64,9"
PS C:\Users\Mayna> $A|Set-Content "test.txt"
PS C:\Users\Mayna> $B = Get-Content "test.txt"
PS C:\Users\Mayna> [Double]$B
649

Apparently Powershell can't handle the ","

I will have a fix next release (probably tonight).

**Comment by petrovsky34** [comment] 2019-05-01 21:51
ok well I will be looking forward to it)))

**Comment by petrovsky34** [comment] 2019-05-01 21:53
windows 8 swarm does not work ???

**Comment by MaynardMiner** [comment] 2019-05-01 21:53
Since you know how- you can try this:

```
function Get-HashRate {
    param(
        [Parameter(Mandatory = $true)]
        [String]$Type,
        [Parameter(Mandatory = $false)]
        [String]$API,
        [Parameter(Mandatory = $false)]
        [Int]$Port
    )

        $HashFile = Get-Content ".\build\txt\$Type-hash.txt"
        $HashFile = $HashFile -replace ",","."
        [decimal]$HashFile
}
```

**Comment by petrovsky34** [comment] 2019-05-01 21:54
windows 8 swarm does not work ???

**Comment by MaynardMiner** [comment] 2019-05-01 21:55
I dunno. I have never tried in Windows 8. I have only supported 10. I can look into it, but I know when I have plugged into a Windows 7 Computer, I had all kinds of issues with gathering data from computer.

**Comment by petrovsky34** [comment] 2019-05-01 21:56
ok

**Comment by petrovsky34** [comment] 2019-05-01 21:56
![zzzzzzzzzzzzzzzzzzzzzz](https://user-images.githubusercontent.com/39003568/57045050-289f1b00-6c75-11e9-9804-b4f8eadb13c8.PNG)

**Comment by MaynardMiner** [comment] 2019-05-01 21:57
Looks right. I tested it, and it worked for me.

**Comment by petrovsky34** [comment] 2019-05-01 22:01
![сссссссссссссссссссссссссссссссссссссссссссссс](https://user-images.githubusercontent.com/39003568/57045299-d14d7a80-6c75-11e9-9bdd-aecb356f42f4.PNG)

**Comment by petrovsky34** [comment] 2019-05-01 22:02
the same thing

**Comment by petrovsky34** [comment] 2019-05-01 22:03
((((I'm crying

**Comment by petrovsky34** [comment] 2019-05-01 22:03
you have no such mistakes as I have???

**Comment by MaynardMiner** [comment] 2019-05-01 22:07
No, I have contacted multiple users, and they state it is running fine.

The only thing I can think of it being, is that your hashrates are 61,00 instead of 61.00. That is the only key difference.

You see the function is really simple. I am surprised it is behaving like this.

**Comment by petrovsky34** [comment] 2019-05-01 22:08
any chance of fixing the problem???

**Comment by MaynardMiner** [comment] 2019-05-01 22:09
Does it save it to stat file as 673,000 now?

It could just be the conversion on screen now.

**Comment by MaynardMiner** [comment] 2019-05-01 22:10
That is a different function.

**Comment by petrovsky34** [comment] 2019-05-01 22:11
![ииииииииииииииииииииииииииииииииии](https://user-images.githubusercontent.com/39003568/57045733-3b1a5400-6c77-11e9-8db2-cb346d308e24.PNG)

**Comment by MaynardMiner** [comment] 2019-05-01 22:12
Okay. I will look at it further. See if I can import Russian settings, as I believe that is cause, which I don't know why.

**Comment by petrovsky34** [comment] 2019-05-01 22:14
I will try to install windows 10 english version tomorrow

**Comment by MaynardMiner** [comment] 2019-05-01 22:21
http://localhost:4099/getstats

Does the hashrate look correct there? Rather than writing to file, I can use the agent's api to get the stats as a workaround.

**Comment by MaynardMiner** [comment] 2019-05-01 22:22
I've been meaning to do that anyways, it's just a lot of work on the HiveOS side to do it that way. (It writes to file for linux HiveOS).

**Comment by MaynardMiner** [comment] 2019-05-01 22:23
It should be in /khs format, so it will be a decimal since it is /hs

**Comment by petrovsky34** [comment] 2019-05-01 22:29
I would hive os put but there swarm is not established

**Comment by petrovsky34** [comment] 2019-05-01 22:30
can't install swarm hive os

**Comment by petrovsky34** [comment] 2019-05-01 22:32
write a new instruction on hiveos s

**Comment by MaynardMiner** [comment] 2019-05-01 22:32
There is an issue right now with HiveOS, I have posted on their github.

You can work around it by running

cd /hive/miners/custom
``git clone https://github.com/MaynardMiner/SWARM.git``

That will install SWARM in custom directory.

Then when you launch, use SWARM as name of custom miner instead of SWARM.number.of.version

**Comment by MaynardMiner** [comment] 2019-05-01 22:34
I will write that as an alternative way to install, in case first fails because HiveOS has issues downloading.

Let me know though if http://localhost:4099/getstats works and shows correct hashrate in /khs. I can fix tonight if it does.

**Comment by petrovsky34** [comment] 2019-05-01 22:35
I'll wait, Yes it will

**Comment by MaynardMiner** [comment] 2019-05-01 22:44
http://localhost:4099/getstats shows correct stats? I didn't understand.

**Comment by petrovsky34** [comment] 2019-05-01 22:47
and this is where

**Comment by MaynardMiner** [comment] 2019-05-01 22:48
Run in browser

**Comment by petrovsky34** [comment] 2019-05-01 22:50
[{"GPU0":{"fans":"48","hashrate":"5580,8050","temperature":"57"}},{"GPU1":{"fans":"50","hashrate":"5750,7280","temperature":"66"}},{"GPU2":{"fans":"50","hashrate":"5574,6910","temperature":"59"}},{"GPU3":{"fans":"50","hashrate":"5705,4230","temperature":"60"}},{"GPU4":{"fans":"50","hashrate":"8757,6810","temperature":"64"}},{"GPU5":{"fans":"50","hashrate":"5662,3780","temperature":"58"}},{"GPU6":{"fans":"50","hashrate":"5580,6810","temperature":"66"}},{"GPU7":{"fans":"50","hashrate":"8891,6690","temperature":"64"}},{"GPU8":{"fans":"50","hashrate":"5680,8180","temperature":"67"}},{"GPU9":{"fans":"50","hashrate":"5616,4540","temperature":"62"}},{"Algorithm":"veil"},{"Uptime":"365"},{"Hash_Units":"KHS"},{"Accepted":"0"},{"Rejected":"0"}]

**Comment by petrovsky34** [comment] 2019-05-01 22:50
veil work algoritms

**Comment by MaynardMiner** [comment] 2019-05-01 22:51
Okay. I will try to get hashrates through that.

**Comment by petrovsky34** [comment] 2019-05-01 22:53
enable gminer now

**Comment by petrovsky34** [comment] 2019-05-01 22:54
problems with gminer only!

**Comment by MaynardMiner** [comment] 2019-05-01 22:59
http://localhost:4099/getstats

Does that show correct for gminer?

This is so crazy that only gminer shows bad stats, they are all gathered the same way.

**Comment by petrovsky34** [comment] 2019-05-01 23:02
Yes gminer is showing wrong everything else is working correctly

**Comment by MaynardMiner** [comment] 2019-05-01 23:04
Very, very weird. I am trying to see if there a way I can record the original number of decimal places before writing the stat, then shifting the decimal place over if it is not in the correct spot.

**Comment by petrovsky34** [comment] 2019-05-01 23:06
ok I'm not good at this pwsh

**Comment by petrovsky34** [comment] 2019-05-01 23:09
ubuntu can't put after installation of drivers and the command sudo nvidia-xconfig -a --coolbits=28 --allowempty-initial-configuration I have a black screen and all that does not work

**Comment by MaynardMiner** [comment] 2019-05-01 23:10
Which version of Ubuntu are you trying to use?

**Comment by petrovsky34** [comment] 2019-05-01 23:12
16.04 18.04 19.04 all has tried

**Comment by petrovsky34** [comment] 2019-05-01 23:12
everywhere the same black screen

**Comment by petrovsky34** [comment] 2019-05-01 23:13
ubuntu lubuntu xubuntu linux mint

**Comment by MaynardMiner** [comment] 2019-05-01 23:15
It is probably because you had nouveau drivers installed.

You likely need to blacklist them.

You can also set nomodeset  in grub.

**Comment by petrovsky34** [comment] 2019-05-01 23:17
driver version 418    430     415    410     390  not work

**Comment by petrovsky34** [comment] 2019-05-01 23:17
nouveau driver not try

**Comment by MaynardMiner** [comment] 2019-05-01 23:21
They are default drivers. They need to be removed from grub or blacklisted. Sometimes drivers fail to do that.

Do me a favor:


1.) open cmd
2.) cd to SWARM directory.
3.) start benchmarking gminer again.

```
powershell
```
THEN:
```
$test = Get-Content ".\build\txt\NVIDIA1-hash.txt"
$test
[Double]$test
[Decimal]$test
[String]$test
```

I want to see what it outputs.

**Comment by petrovsky34** [comment] 2019-05-01 23:24
cd to SWARM directory
swarm folder on desktop how to write me

**Comment by petrovsky34** [comment] 2019-05-01 23:25
![1232131232131231](https://user-images.githubusercontent.com/39003568/57049632-95b8ad80-6c81-11e9-82a6-3ef0b3b618ea.PNG)

**Comment by MaynardMiner** [comment] 2019-05-01 23:26
Open cmd.exe

start > run > cmd.exe

cd \
cd users\[username]\Desktop\SWARM.2.2.3

**Comment by petrovsky34** [comment] 2019-05-01 23:31
![33333](https://user-images.githubusercontent.com/39003568/57049817-60608f80-6c82-11e9-8e5b-c08b8b90c322.PNG)

**Comment by MaynardMiner** [comment] 2019-05-01 23:32
Is nvidia1-hash.txt empty right now?

**Comment by petrovsky34** [comment] 2019-05-01 23:33
swarm must be running??

**Comment by petrovsky34** [comment] 2019-05-01 23:33
0

**Comment by petrovsky34** [comment] 2019-05-01 23:34
yes

**Comment by MaynardMiner** [comment] 2019-05-01 23:34
Yes, it should be running, and gminer should be started, and hash on screen.

**Comment by MaynardMiner** [comment] 2019-05-01 23:34
I want to see if $Test matches screen

**Comment by petrovsky34** [comment] 2019-05-01 23:38
![444444](https://user-images.githubusercontent.com/39003568/57050039-4c695d80-6c83-11e9-9b9a-5f85fb10fa90.PNG)
 work))))

**Comment by MaynardMiner** [comment] 2019-05-01 23:39
?

How much system resource you use? Is your disk-space full?

**Comment by petrovsky34** [comment] 2019-05-01 23:40
![cxczxczxc](https://user-images.githubusercontent.com/39003568/57050097-97837080-6c83-11e9-845a-09629546bc8e.PNG)

**Comment by MaynardMiner** [comment] 2019-05-01 23:41
hmmm. Very weird.

If you see it happen again, then run that $Test command, and post here so I can debug.

**Comment by petrovsky34** [comment] 2019-05-01 23:41
![535353535475665856856](https://user-images.githubusercontent.com/39003568/57050130-c26dc480-6c83-11e9-832a-81ab7a3397e9.PNG)

**Comment by petrovsky34** [comment] 2019-05-01 23:42
ok fix in next version of swarm

**Comment by MaynardMiner** [comment] 2019-05-01 23:43
lol I would if I know what is wrong. I will do what I can.

**Comment by petrovsky34** [comment] 2019-05-01 23:45
what time do you have???

**Comment by petrovsky34** [comment] 2019-05-01 23:45
night or day

**Comment by petrovsky34** [comment] 2019-05-01 23:48
thank you good night)))

**Comment by MaynardMiner** [comment] 2019-05-01 23:50
Midwest US- Evening

**Comment by petrovsky34** [comment] 2019-05-01 23:51
thank you good night)))

thank thank thank thank

**Comment by MaynardMiner** [comment] 2019-05-01 23:54
Same to you.

I don't have a Russian version of Windows setup, so I don't know if I can 100% fix. I can only just try to change things, and you can report back in, and let me know if it still has issues.

**Comment by petrovsky34** [comment] 2019-05-01 23:55
ok 
in the morning I will put windows 10 english version

**Comment by petrovsky34** [comment] 2019-05-01 23:57
thank you friend. God bless you!

**Comment by MaynardMiner** [comment] 2019-05-02 00:07
![image](https://user-images.githubusercontent.com/38481606/57050830-8408e300-6c4c-11e9-94f8-f091ad7bc4e1.png)

I was able to reproduce:

When I set the default culture to 'ru-RU' (Russian it happens).

So I assume if I force the culture one I know that works: 'en-US' (English US), I believe it will fix it. It will be in next release.

**Comment by petrovsky34** [comment] 2019-05-02 00:09
спасибо буду ждать релиза 2.2.4 swarm

**Comment by petrovsky34** [comment] 2019-05-02 00:10
thank you will wait for the release of 2.2.4 swarm

**Comment by MaynardMiner** [comment] 2019-05-02 13:42
On main git page, green button- "Clone or Download"

Download the source as .zip. Extract it, and run it like you normally would.

It has what I believe is the fix. I would like to know I fixed it before I add to next release.

I have the two main threads for EN-US culture for items like math and date/time. I also made it so that the RAM counter is use CIMinstance instead of ``systeminfo``

**Comment by petrovsky34** [comment] 2019-05-02 14:23
![Capture](https://user-images.githubusercontent.com/39003568/57082232-6187d000-6d07-11e9-901e-75e1a12262be.PNG)

**Comment by petrovsky34** [comment] 2019-05-02 14:25
Hello how to fix it???

**Comment by petrovsky34** [comment] 2019-05-02 14:32
![33432](https://user-images.githubusercontent.com/39003568/57082875-4796bf00-6d00-11e9-8d1b-3764336b1765.PNG)

**Comment by petrovsky34** [comment] 2019-05-02 14:32
Hello how to fix it???

**Comment by MaynardMiner** [comment] 2019-05-02 17:26
Hold on.

I think I pushed something I shouldn't have pushed. Because it wasn't ready yet.

**Comment by MaynardMiner** [comment] 2019-05-02 17:32
I checked. That should be fine. You are using the correct -Type arguments, right?

**Comment by MaynardMiner** [comment] 2019-05-02 17:40
The only thing I can see that would cause devicelist.txt not being created, is if there is an issue with the arguments. Please double check to make sure there isn't a typo, if not, I will get you the command SWARM uses to get the list of devices on PC. You can run the command ``get parameters`` to make sure they match your batch file (in case of typo).

```
powershell
get-wmiobject -namespace root\cimv2 -class Win32_PnPEntity
```

Is the command it runs to get the list of devices, then formats them to file. But only formats them if ``-Type `` argument is ``NVIDIA1,NVIDIA2,NVIDIA3 or AMD1``

**Comment by petrovsky34** [comment] 2019-05-02 17:43
on Windows 8 so writes

**Comment by MaynardMiner** [comment] 2019-05-02 17:44
Ah.

Yeah, windows 8 many not have get-wmiobject.

However, you may be able to update powershell to get it. Let me look into it.

**Comment by petrovsky34** [comment] 2019-05-02 17:44
I installed Windows 10 waiting for driver installation

**Comment by petrovsky34** [comment] 2019-05-02 17:45
put Windows 10 that there were no problems

**Comment by petrovsky34** [comment] 2019-05-02 17:46
it's a pity that Windows 8 not working there is better 4гиговые cards and 3 rules are working more algorithms operates

**Comment by petrovsky34** [comment] 2019-05-02 17:47
what video cards do you have???

**Comment by petrovsky34** [comment] 2019-05-02 17:47
2080ti ???

**Comment by MaynardMiner** [comment] 2019-05-02 17:48
Yeah. You may be able to use Windows 8, but you will have update .NET framework, and likely other. I'm not sure however if the registries are the same, for attaining information on GPU's, RAM, etc. That is why I only support Windows 10.

I suppose once I finish helping another user build a website for monitoring- I will look into building a 'lighter' version in which SWARM will run without having to pull all that information, so it will work on all windows.

Yes. Works with 2080ti, however, some users have issues with the fan control. Some users it works for them, others it doesn't. But mining wise is good.

**Comment by petrovsky34** [comment] 2019-05-02 17:50
I ask what you have video card

**Comment by petrovsky34** [comment] 2019-05-02 17:51
well if you do that would Windows 8 worked!!!

**Comment by MaynardMiner** [comment] 2019-05-02 17:51
Vegas, RX580, 2070, 1080ti, 1050ti, 1070.

I buy when I can find good prices.

**Comment by petrovsky34** [comment] 2019-05-02 17:53
I have cheap maps 1050 tix 8 1063 x2

**Comment by MaynardMiner** [comment] 2019-05-02 17:53
I mainly use Windows for AMD, Linux for NVIDIA. (but I have cards on both for testing). I find it works best, if you set them both up right.

**Comment by petrovsky34** [comment] 2019-05-02 17:55
know what not whether the analogues time viewer???

**Comment by MaynardMiner** [comment] 2019-05-02 17:59
analogues time veiwer? I think bad translation. Not sure what you mean.

I have to step away. Be back later to check in.

There is a discord with 200 users who can help you.

**Comment by petrovsky34** [comment] 2019-05-02 18:01
ok

**Comment by MaynardMiner** [comment] 2019-05-03 03:36
If you download the .zip from master again-

I believe it will work on Windows 8.

But SWARM now requires Powershell Core and latest .NET:

https://github.com/PowerShell/PowerShell/releases
https://dotnet.microsoft.com/download/dotnet-framework/net472

If you could test for me, it would be helpful.

**Comment by MaynardMiner** [comment] 2019-05-03 06:01
Proposed fix in 2.2.4 release

**Comment by petrovsky34** [comment] 2019-05-03 08:49
ok

**Comment by petrovsky34** [comment] 2019-05-03 10:37
work windows 8.1 super)))

**Comment by petrovsky34** [comment] 2019-05-03 10:38
thanks

**Comment by petrovsky34** [comment] 2019-05-03 10:39
add cuda 9.1 
gtx 1000 version best hasrate 
please

**Comment by petrovsky34** [comment] 2019-05-03 13:22
![Capture333](https://user-images.githubusercontent.com/39003568/57140116-aa9b5b00-6dbf-11e9-9768-4638ddd40d37.PNG)

**Comment by MaynardMiner** [comment] 2019-05-03 13:29
Is this happening with new version?

Windows 8 or 10?

**Comment by petrovsky34** [comment] 2019-05-03 13:35
windows 8

**Comment by MaynardMiner** [comment] 2019-05-03 13:37
And is the error only for $global:gpupower ? I just to make sure it is just gpupower, or of it is throwing for gpufans and temps as well.

**Comment by petrovsky34** [comment] 2019-05-03 13:42
it's okay!!! stats cleaner

**Comment by petrovsky34** [comment] 2019-05-03 13:49
and how to enable auto-update

**Comment by MaynardMiner** [comment] 2019-05-03 13:49
So it works now?

I was concerned whether or not Swarm will record fans,temps,power in Windows 8.

If the error continue, post .\build\txt\devicelist.txt. I would like to see if it detecting gpus.

**Comment by petrovsky34** [comment] 2019-05-03 13:51
it's okay!!!

**Comment by petrovsky34** [comment] 2019-05-03 13:53
![4543533](https://user-images.githubusercontent.com/39003568/57141872-f2bc7c80-6dc3-11e9-9019-f2b2ce80296c.PNG)

**Comment by petrovsky34** [comment] 2019-05-03 13:53
x10

**Comment by petrovsky34** [comment] 2019-05-03 13:55
windows 10 write 10 gpu
windows 8 write 1 gpu

**Comment by MaynardMiner** [comment] 2019-05-03 13:56
```
pwsh
Get-CimInstance -namespace root\cimv2 -class Win32_PnPEntity | Where PNPClass -Eq "Display"
```

Does it list your gpus?

**Comment by petrovsky34** [comment] 2019-05-03 14:00
it's okay!!!

Work)))

**Comment by MaynardMiner** [comment] 2019-05-03 14:04
There must be a compatibility issue with gpu detection. I am going to close this post, and open new issue for auto gpu detection in win 7/8

**Closed** 2019-05-03 14:04 UTC
Labels: proposed fix applied, single-user bug, windows
