### ISSUE TITLE
Issue with nanominer-n-1 script.... 

### ISSUE THREAD

**Issue by UserDC-LeGrand** [MaynardMiner/SWARM#385] opened 2022-10-18 18:44 UTC
Noticed issue with Nanominer-n-1 script which passes wrong arguments (none [octopus], which prevents the miner from starting, and bans it from SWARM execution...

nanominer-n-1 6 00 Hours 00 Minutes _****5 Times****_  

nanominer **none [octopus]** wallet=1234567890-abcdefg.rig3-SWARM pool1=octopus.auto.nicehash.com:9200 webport=9091                                             logPath=/hive/miners/custom/SWARM.3.6.4.linux/logs/NVIDIA1.log rigPassword=x

![image](https://user-images.githubusercontent.com/99490445/196516122-3abbe03c-39a6-4b7f-bf18-50e5ce98108a.png)

**Comment by MaynardMiner** [comment] 2022-10-18 19:35
I see issue will fix.

**Comment by MaynardMiner** [comment] 2022-10-18 20:12
https://github.com/nanopool/nanominer#configuration-file

Example configuration files for reference.

**Comment by MaynardMiner** [comment] 2022-10-18 22:51
![image](https://user-images.githubusercontent.com/38481606/196559643-8a1b7b01-bc19-4e89-b12b-f5f559abf5bc.png)


Nanominer benches for me atm. It is considerably slower than t-rex version when comparing it in ``get benchmarks`` command. So not sure if you want to put effort in to find out why.

**Comment by UserDC-LeGrand** [comment] 2022-10-19 04:01
Thanks for all the pointers. 

BTW, your 3.6.5 /bin/miner .sh scripts are pointing to the prior release deleted folder... 

For example, see laset line in  swarm_start_ethash.sh  ...

#!/usr/bin/env bash
export LD_LIBRARY_PATH=/usr/local/swarm/lib64:/hive/miners/custom/SWARM.3.6.4.linux/bin/nanominer-n-1
sleep .1
export DISPLAY=:0
sleep .1
/hive/miners/custom/SWARM**.3.6.4.l**inux/bin/nanominer-n-1/nanominer

**Comment by MaynardMiner** [comment] 2022-10-19 21:26
Not really a bug- The scripts are written when SWARM launches the miner.

**Comment by MaynardMiner** [comment] 2022-10-22 08:33
Closing because I can't reproduce as notated above

**Closed by MaynardMiner** 2022-10-22 08:33 UTC
Labels: single-user bug
